# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: huggingface-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.huggingface.token | b64enc | quote }}